# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Tinder-Uklon-Edition' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  # Pods for Tinder-Uklon-Edition
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'CocoaLumberjack/Swift'
end
